name: CI-Pipeline

on:
    push:
        branches:
            - pipeline


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Dotnet
              uses: actions/setup-dotnet@v6
              with:
                dotnet-version: '10.0.x'
            - name: Build Code
              run: dotnet build 
            - name: Run Unit Tests
              run: dotnet test ./tests/TaskManagement.UnitTests
            - name: Run Integration Tests
              run: dotnet test ./tests/TaskManagement.IntegrationTests
              
